nmb1=int(input("Enter the 1st number: "))
nmb2=int(input("Enter the 2nd number: "))
nmb3=int(input("Enter the 3rd number: "))
nmb4=int(input("Enter the 4th number: "))
nmb5=int(input("Enter the 5th number: "))
nmb6=int(input("Enter the 6th number: "))
nmb7=int(input("Enter the 7th number: "))
nmb8=int(input("Enter the 8th number: "))

s1=set()
s1.add(nmb1)
s1.add(nmb2)
s1.add(nmb3)
s1.add(nmb4)
s1.add(nmb5)
s1.add(nmb6)
s1.add(nmb7)
s1.add(nmb8)
print(s1)